Changes to composite mass modeling
sibirrer/hierArc pull request #26
Opened 2024-01-05 00:38 UTC by williyamshoe

Changes include:

- Bug fixes
- QoL changes 
    - ability to specify kappa_s and r_scale_angle distributions instead of rho0 and r_scale
    - ability to bypass MGE if provided light profile is already "MULTI_GAUSSIAN"
    - providing amp_2_luminosity parameter in KinConstraintsComposite to help intuit converting amplitudes to correct units
- Changed population level m2l to log_m2l
- Functionality to input M/L distribution, and so to not model population-level M/L
    - see KinConstraintsCompositeM2l subclass

2024-01-06 00:44 UTC, ajshajib commented
@williyamshoe, the formatting check is failing. You can run these commands locally and then push a commit to resolve this:

```
black .
docformatter -r ./* --black --in-place
```
You can `pip install black` and `docformatter` if needed.

2024-01-09 03:48 UTC, ajshajib requested changes

2024-01-09 03:48 UTC, ajshajib commented on hierarc/Likelihood/parameter_scaling.py
> +        self.log_m2l_population_lvl = False
```suggestion
        self._is_log_m2l_population_level = False
```

2024-01-09 03:48 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite_m2l.py
I wonder if it would be possible to avoid a new subclass to remove M/L interpolation and have it already done within the existing `KinConstraintsComposite` class using a flag `self._is_m2l_population_level`. If needed, it's okay to have class methods that would be used only for `self._is_m2l_population_level = False`, and vice versa.

2024-01-09 03:48 UTC, ajshajib commented on hierarc/Likelihood/hierarchy_likelihood.py
> +            anisotropy, gamma_in, and log(m2l). In that case, gamma_in_array and log_m2l_array need to be provided.
```suggestion
            anisotropy, gamma_in, and log_m2l. In that case, gamma_in_array and log_m2l_array need to be provided.
```

2024-01-09 03:48 UTC, ajshajib commented on hierarc/Likelihood/parameter_scaling.py
> +        self.log_m2l_population_lvl = False
The part "is" denotes that this variable is a boolean flag. The "_" at the beginning is if this class variable is not supposed to be accessed outside its own class methods.

2024-01-09 23:21 UTC, williyamshoe commented on hierarc/LensPosterior/kin_constraints_composite.py
> +            while np.isnan(j_kin) and c < 10:
Thanks!  I narrowed it down to a bug in my local version, and so I've removed these lines from the branch!

2024-01-10 14:28 UTC, ajshajib commented
@williyamshoe, thanks a lot for making the changes! Are you done implementing them, or is it still in progress?

2024-01-10 17:47 UTC, williyamshoe commented
> @williyamshoe, thanks a lot for making the changes! Are you done implementing them, or is it still in progress?

Yup, I'm done implementing the changes!

2024-01-22 19:15 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +    def arrays_check(array0, array1):
```suggestion
    def _arrays_check(array0, array1):
```

2024-01-22 19:17 UTC, ajshajib requested changes

2024-01-22 19:17 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +            )
```suggestion
        if self._arrays_check(kappa_s_array, r_s_angle_array):
            self._kappa_s_array = kappa_s_array
            self._r_scale_angle_array = r_s_angle_array
        elif self._arrays_check(rho0_array, r_s_array):
            self._kappa_s_array, self._r_scale_angle_array = self.get_kappa_s_r_s_angle(
                rho0_array, r_s_array
            )
```

2024-01-22 19:17 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +        ):
```suggestion
        if not is_m2l_population_level and not self._arrays_check(
            self._kappa_s_array, log_m2l_array
        ):
```

2024-01-22 19:23 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +    def _arrays_check(array0, array1):
Needs a docstring for this function.

2024-01-22 19:24 UTC, ajshajib commented
@williyamshoe, looks good to me, except for I requested a docstring to be added. I also changed the method name to `_check_arrays()` to make it explicit that it's a private method.

2024-01-22 19:26 UTC, ajshajib requested changes

2024-01-22 19:26 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +    def _arrays_check(array0, array1):
```suggestion
    def _check_arrays(array0, array1):
```

2024-01-22 19:26 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +        elif self._arrays_check(rho0_array, r_s_array):
```suggestion
        if self._check_arrays(kappa_s_array, r_s_angle_array):
            self._kappa_s_array = kappa_s_array
            self._r_scale_angle_array = r_s_angle_array
        elif self._check_arrays(rho0_array, r_s_array):
```

2024-01-22 19:26 UTC, ajshajib commented on hierarc/LensPosterior/kin_constraints_composite.py
> +        if not is_m2l_population_level and not self._arrays_check(
```suggestion
        if not is_m2l_population_level and not self._check_arrays(
```

2024-01-22 20:54 UTC, ajshajib approved these changes

2024-01-22 20:55 UTC, merged

2024-01-22 20:58 UTC, ajshajib commented
@williyamshoe, oops, I missed to check the coverage report before merging! Line 535 in kin_constraints_composite.py is missing coverage. If possible, can you make a quick PR to cover that line?